/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.0.0/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)

    implementation("org.openjfx:javafx-base:25:win")
    implementation("org.openjfx:javafx-graphics:25:win")
    implementation("org.openjfx:javafx-controls:25:win")
    implementation("org.openjfx:javafx-fxml:25:win")
    implementation("org.openjfx:javafx-media:25:win")
    // implementation("org.openjfx:javafx-web:25:win")
    // implementation("org.openjfx:javafx-swing:25:win")
    implementation("com.github.almasb:fxgl:21.1")
    implementation("com.mysql:mysql-connector-j:9.4.0")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

application {
    // Define the main class for the application.
    mainClass = "autodrivedash.App"
    applicationDefaultJvmArgs = listOf(
        "--enable-native-access=ALL-UNNAMED"
    )
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
